name: TF_STATE
on:
  push:
    branches:
      - main
  pull_request:
#env:
#  AWS_ACCOUNT: '407026129471'
#  AWS_REGION: 'eu-west-2'
permissions:
  id-token: write
  contents: read
jobs:
  Initialise_state_file_repoository:
    runs-on: [self-hosted, linux, X64]
#   runs-on: ubuntu-latest  

    steps:
      - name: Git clone the repository
        uses: actions/checkout@master
        
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sts GetCallerIdentity
        run:
          aws sts get-caller-identity

#      - uses: hashicorp/setup-terraform@v3.0.0
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Init
        run: |
          echo "Terraform Init"...
          echo "Branch ${{ github.ref }}"...        # refs/head/main
          echo "Branch ${{ github.base_ref }}"...
          echo "Branch ${{ github.ref_name }}"...   # main
          echo "Branch ${{ github.ref_type }}"...   # branch
          echo "Branch ${{ github.workspace }}"...  # /home/paul/actions-runner/_work/github_tf_states/github_tf_states
          terraform init

      - name: Terraform Validate
        run: |
          echo "Terraform Validate"...
          terraform validate

      - name: Terraform Format
        run: |
          echo "Terraform Format"...
          terraform fmt

      - name: Terraform Plan
        run: |
          echo "Terraform Plan"...
          terraform plan
