name: TF_STATE
on:
  push:
    branches:
      - main
  pull_request:
env:
  AWS_REGION: 'eu-west-2'
permissions:
  id-token: write
  contents: read
jobs:
  AssumeRoleAndCallIdentity:
    runs-on: self-hosted
#    runs-on: ubuntu-latest  
    steps:
      - name: Git clone the repository
        uses: actions/checkout@master

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::407026129471:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Sts GetCallerIdentity
        run:
          aws sts get-caller-identity

      - uses: hashicorp/setup-terraform@v1
      - name: Checkout

        uses: actions/checkout@v2
      - name: TF init and validate
        run: |
          echo "Validating $EXAMPLE"...
          terraform init && terraform validate
