name: TF_STATE
on:
  push:
    branches:
      - main
  pull_request:
env:
  AWS_ACCOUNT: '407026129471'
  AWS_REGION: 'eu-west-2'
permissions:
  id-token: write
  contents: read
jobs:
  Initialise state file repoository:
    runs-on: [self-hosted, linux, X64]
#    runs-on: ubuntu-latest  
    steps:
      - name: Git clone the repository
        uses: actions/checkout@master

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Sts GetCallerIdentity
        run:
          aws sts get-caller-identity
  Check terraform setup:
    runs-on: [self-hosted, linux, X64]
    steps:
#      - uses: hashicorp/setup-terraform@v3.0.0
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Init
        run: |
          echo "Terraform Init"...
          terraform init

      - name: Terraform Validate
        run: |
          echo "Terraform Validate"...
          terraform validate

      - name: Terraform Format
        run: |
          echo "Terraform Format"...
          terraform fmt
