name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest  
    steps:
      - name: Git clone the repository
        uses: actions/checkout@master

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::407026129471:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Sts GetCallerIdentity
        run:
          aws sts get-caller-identity
          
  validate-terraform:
    name: Validate Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: examples
    steps:
      - uses: hashicorp/setup-terraform@v1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check examples
        env:
          EXAMPLES: simple
        run: |
          for EXAMPLE in ${EXAMPLES}
          do
            echo "Validating $EXAMPLE"...
            cd $EXAMPLE && terraform init && terraform validate && cd -
          done
